/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mustang(props) {
  const { nodes, materials } = useGLTF('/Mustang.gltf')
  console.log("Mustang color: ", props.carPaint);
  return (
    <group {...props} dispose={null}>
      <pointLight intensity={0.7} decay={2} position={[1.72, 1.57, 0.82]} rotation={[-0.54, 0.74, 0.38]} />
      <pointLight intensity={0.7} decay={2} position={[-1.7, 1.57, 0.82]} rotation={[-0.45, -0.79, 2.2]} />
      <pointLight intensity={0.7} decay={2} position={[-1.7, 1.23, -3.64]} rotation={[-3.01, -0.44, 2.17]} />
      <pointLight intensity={0.7} decay={2} position={[-1.7, 1.23, 3.25]} rotation={[-0.42, -0.62, 2.08]} />
      <pointLight intensity={0.7} decay={2} position={[0.92, 0.12, 3.38]} rotation={[-0.54, 0.74, 0.38]} />
      <pointLight intensity={0.7} decay={2} position={[-0.14, 0.93, -3.56]} rotation={[-0.54, 0.74, 0.38]} />
      <pointLight intensity={0.7} decay={2} position={[1.82, 1.23, -3.15]} rotation={[-3.01, -0.44, 2.17]} />
      <group position={[0.28, 0, -0.16]} rotation={[Math.PI / 2, 0, -Math.PI / 4]} scale={[1, 1.23, 1]}>
        <mesh geometry={nodes.Circle_1.geometry} material={materials[props.carPaint]} />
        <mesh geometry={nodes.Circle_2.geometry} material={materials['Glass-material']} />
        <mesh geometry={nodes.Circle_3.geometry} material={materials['Rims-material']} />
        <mesh geometry={nodes.Circle_4.geometry} material={materials['Headlights-emission-material']} />
        <mesh geometry={nodes.Circle_5.geometry} material={materials['Tire-material']} />
        <mesh geometry={nodes.Circle_6.geometry} material={materials['Green-paint']} />
        <mesh geometry={nodes.Circle_7.geometry} material={materials['Blue-paint']} />
        <mesh geometry={nodes.Circle_8.geometry} material={materials['Black-paint']} />
        <mesh geometry={nodes.Circle_9.geometry} material={materials['Orange-paint']} />
        <group position={[-1.18, 0.47, -0.26]} scale={[0.23, 0.19, 0.23]}>
          <mesh geometry={nodes.Circle004_1.geometry} material={materials['Rims-material']} />
          <mesh geometry={nodes.Circle004_2.geometry} material={materials['Tire-material']} />
        </group>
        <group position={[0.85, 0.47, -0.26]} scale={[0.23, 0.19, 0.23]}>
          <mesh geometry={nodes.Circle001_1.geometry} material={materials['Rims-material']} />
          <mesh geometry={nodes.Circle001_2.geometry} material={materials['Tire-material']} />
        </group>
        <mesh geometry={nodes.Circle002_1.geometry} material={materials['Red-light-material']} />
        <mesh geometry={nodes.Circle002_2.geometry} material={materials['Red-light-emission-material']} />
        <mesh geometry={nodes.Circle004.geometry} material={materials['Rims-material']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Mustang.gltf')

export default Mustang;